### ISSUE TITLE
Wup server modified files wont save on reboot

### ISSUE THREAD

**Issue by Aryamanee** [GaryOderNichts/bluubomb#7]
I have tried wupserver and ftpiiu for modifying files on the mlc but upon reboot none of them save regardless of if i use the wupserver binary or the loadrpx binary for ftpiiu everywhere. Even ftp by laf111 wont work.

**Comment by Aryamanee** [comment]
I am using mocha cfw and I can boot into homebrew, even install titles(If this matters)

**Comment by GaryOderNichts** [comment]
This is probably caused by the caching the mlc is doing.
If the console isn't shut down properly the cache isn't flushed and the changes are lost.
Try using [this modified wupclient](https://gist.github.com/GaryOderNichts/409672b1bd5627b9dc506fe0f812ec9e) and run `flush_mlc()` to flush the cache manually.

**Comment by Aryamanee** [comment]
ok

**Comment by Aryamanee** [comment]
Thanks for your reply

**Comment by Aryamanee** [comment]
It works well, thanks so much!
